<a href="https://colab.research.google.com/github/isaackurniawan/NaiveBayes/blob/main/naive_bayes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [4]:
dataset = pd.read_csv("Social_Network_Ads.csv")
x = dataset.iloc[:, [2,3]].values 
y = dataset.iloc[:, -1].values

In [5]:
print(x)

[[    19  19000]
 [    35  25000]
 [    26  30000]
 [    27  67000]
 [    19  70000]
 [    27  58000]
 [    27  85000]
 [    32 150000]
 [    25  33000]
 [    35  65000]
 [    26  80000]
 [    26  52000]
 [    20  86000]
 [    32  18000]
 [    18  82000]
 [    29  80000]
 [    47  25000]
 [    45  26000]
 [    46  28000]
 [    48  29000]
 [    45  22000]
 [    47  49000]
 [    48  41000]
 [    45  22000]
 [    46  23000]
 [    47  20000]
 [    49  28000]
 [    47  30000]
 [    29  43000]
 [    31  18000]
 [    31  74000]
 [    27 137000]
 [    21  16000]
 [    28  44000]
 [    27  90000]
 [    35  27000]
 [    33  28000]
 [    30  49000]
 [    26  72000]
 [    27  31000]
 [    27  17000]
 [    33  51000]
 [    35 108000]
 [    30  15000]
 [    28  84000]
 [    23  20000]
 [    25  79000]
 [    27  54000]
 [    30 135000]
 [    31  89000]
 [    24  32000]
 [    18  44000]
 [    29  83000]
 [    35  23000]
 [    27  58000]
 [    24  55000]
 [    23  48000]
 [    28  79000]
 [    22  1800

In [6]:
print(y)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1
 1 1 0 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0
 1 1 0 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0
 0 1 0 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0 1 1 1 0 1 1 1 1 0 1
 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1]


In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)

In [9]:
print(x_train)

[[    44  39000]
 [    32 120000]
 [    38  50000]
 [    32 135000]
 [    52  21000]
 [    53 104000]
 [    39  42000]
 [    38  61000]
 [    36  50000]
 [    36  63000]
 [    35  25000]
 [    35  50000]
 [    42  73000]
 [    47  49000]
 [    59  29000]
 [    49  65000]
 [    45 131000]
 [    31  89000]
 [    46  82000]
 [    47  51000]
 [    26  15000]
 [    60 102000]
 [    38 112000]
 [    40 107000]
 [    42  53000]
 [    35  59000]
 [    48  41000]
 [    48 134000]
 [    38 113000]
 [    29 148000]
 [    26  15000]
 [    60  42000]
 [    24  19000]
 [    42 149000]
 [    46  96000]
 [    28  59000]
 [    39  96000]
 [    28  89000]
 [    41  72000]
 [    45  26000]
 [    33  69000]
 [    20  82000]
 [    31  74000]
 [    42  80000]
 [    35  72000]
 [    33 149000]
 [    40  71000]
 [    51 146000]
 [    46  79000]
 [    35  75000]
 [    38  51000]
 [    36  75000]
 [    37  78000]
 [    38  61000]
 [    60 108000]
 [    20  82000]
 [    57  74000]
 [    42  65000]
 [    26  8000

In [10]:
print(x_test)

[[    30  87000]
 [    38  50000]
 [    35  75000]
 [    30  79000]
 [    35  50000]
 [    27  20000]
 [    31  15000]
 [    36 144000]
 [    18  68000]
 [    47  43000]
 [    30  49000]
 [    28  55000]
 [    37  55000]
 [    39  77000]
 [    20  86000]
 [    32 117000]
 [    37  77000]
 [    19  85000]
 [    55 130000]
 [    35  22000]
 [    35  47000]
 [    47 144000]
 [    41  51000]
 [    47 105000]
 [    23  28000]
 [    49 141000]
 [    28  87000]
 [    29  80000]
 [    37  62000]
 [    32  86000]
 [    21  88000]
 [    37  79000]
 [    57  60000]
 [    37  53000]
 [    24  58000]
 [    18  52000]
 [    22  81000]
 [    34  43000]
 [    31  34000]
 [    49  36000]
 [    27  88000]
 [    41  52000]
 [    27  85000]
 [    35  25000]
 [    43 112000]
 [    27  58000]
 [    37  80000]
 [    52  90000]
 [    26  30000]
 [    49  86000]
 [    57 122000]
 [    34  25000]
 [    35  57000]
 [    34 115000]
 [    59  88000]
 [    45  32000]
 [    29  83000]
 [    26  80000]
 [    49  2800

In [11]:
print (y_train)

[0 1 0 1 1 1 0 0 0 0 0 0 1 1 1 0 1 0 0 1 0 1 0 1 0 0 1 1 1 1 0 1 0 1 0 0 1
 0 0 1 0 0 0 0 0 1 1 1 1 0 0 0 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 1 1 0 0 1 0 1
 1 1 0 0 1 1 0 0 1 1 0 1 0 0 1 1 0 1 1 1 0 0 0 0 0 1 0 0 1 1 1 1 1 0 1 1 0
 1 0 0 0 0 0 0 0 1 1 0 0 1 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 1 0 0 0 1 1 0 0
 0 0 1 0 1 0 0 0 1 0 0 0 0 1 1 1 0 0 0 0 0 0 1 1 1 1 1 0 1 0 0 0 0 0 1 0 0
 0 0 0 0 1 1 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 0 1 1 0 0 0 0 1 0 0 0 0 1 0 1 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 1 0 0 0
 0 0 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 1 1 0 0 0 0 1
 0 0 0 0]


In [12]:
print(y_test)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 0 0 0 0 1 1 0 0 0 0
 0 0 1 0 0 0 0 1 0 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 1 0 1 0 1 0 0 0 0 1 0 0 1
 0 0 0 0 1 1 1 0 0 0 1 1 0 1 1 0 0 1 0 0 0 1 0 1 1 1]


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.fit_transform(x_test)

In [14]:
print(x_train)

[[ 0.58164944 -0.88553854]
 [-0.60673761  1.46057861]
 [-0.01254409 -0.56693004]
 [-0.60673761  1.89504474]
 [ 1.37390747 -1.4068979 ]
 [ 1.47293972  0.99714806]
 [ 0.08648817 -0.79864531]
 [-0.01254409 -0.24832153]
 [-0.21060859 -0.56693004]
 [-0.21060859 -0.19039272]
 [-0.30964085 -1.29104026]
 [-0.30964085 -0.56693004]
 [ 0.38358493  0.09925138]
 [ 0.8787462  -0.59589444]
 [ 2.06713324 -1.17518263]
 [ 1.07681071 -0.1324639 ]
 [ 0.68068169  1.77918711]
 [-0.70576986  0.56268192]
 [ 0.77971394  0.35993106]
 [ 0.8787462  -0.53796563]
 [-1.20093113 -1.58068436]
 [ 2.1661655   0.93921924]
 [-0.01254409  1.22886333]
 [ 0.18552042  1.08404129]
 [ 0.38358493 -0.48003681]
 [-0.30964085 -0.30625035]
 [ 0.97777845 -0.82760972]
 [ 0.97777845  1.86608033]
 [-0.01254409  1.25782774]
 [-0.90383437  2.27158206]
 [-1.20093113 -1.58068436]
 [ 2.1661655  -0.79864531]
 [-1.39899564 -1.46482672]
 [ 0.38358493  2.30054647]
 [ 0.77971394  0.76543279]
 [-1.00286662 -0.30625035]
 [ 0.08648817  0.76543279]
 

In [15]:
print(x_test)

[[-0.54748976  0.51423265]
 [ 0.15442019 -0.61965341]
 [-0.10879604  0.14648582]
 [-0.54748976  0.2690681 ]
 [-0.10879604 -0.61965341]
 [-0.81070599 -1.53902048]
 [-0.45975102 -1.69224833]
 [-0.0210573   2.26103009]
 [-1.60035469 -0.06803316]
 [ 0.94406888 -0.83417239]
 [-0.54748976 -0.65029898]
 [-0.72296725 -0.46642556]
 [ 0.06668145 -0.46642556]
 [ 0.24215893  0.20777696]
 [-1.4248772   0.48358708]
 [-0.37201227  1.43359973]
 [ 0.06668145  0.20777696]
 [-1.51261594  0.45294151]
 [ 1.64597884  1.83199213]
 [-0.10879604 -1.47772935]
 [-0.10879604 -0.71159012]
 [ 0.94406888  2.26103009]
 [ 0.41763642 -0.58900784]
 [ 0.94406888  1.0658529 ]
 [-1.16166097 -1.29385593]
 [ 1.11954637  2.16909339]
 [-0.72296725  0.51423265]
 [-0.63522851  0.29971367]
 [ 0.06668145 -0.25190658]
 [-0.37201227  0.48358708]
 [-1.33713846  0.54487822]
 [ 0.06668145  0.2690681 ]
 [ 1.82145632 -0.31319772]
 [ 0.06668145 -0.5277167 ]
 [-1.07392223 -0.37448886]
 [-1.60035469 -0.55836227]
 [-1.24939971  0.33035924]
 

In [24]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit = (x_train, y_train)

# New Section

In [26]:
from matplotlib.colors import ListedColormap
x_set, y_set = x_train, y_train
x1, x2 = np.meshgrid(np.arange(start = x_set[:, 0 ].min()-1, stop = x_set[:,0].max()+1, step=0.01),
                     np.arange(start = x_set[:, 1 ].min()-1, stop = x_set[:,0].max()+1, step=0.01))
plt.contour(x1,x2, classifier.predict(np.array([x1.ravel(), x2.ravel()]).T).reshape(x1.reshape),
            alpha = 0.75, cmap = ListedColormap(('red','green')))
plt.xlim(x1.min(),x1.max())
plt.ylim(x2.min(),x2.max())
for i, j in enumerate (np.unique(y_set)):
  plt.scatter(x_set[y_set == j,0], x_set[y_set==j, 1],
              c = ListedColormap(('red', 'green'))(i),label = j)
  plt.title('Kasifikasi Data dengan Naiive Bayes(Data Training)')
  plt.xlabel('Umur')
  plt.ylabel('Estimasi gaji')
  plt.legend()
  plt.show()


NotFittedError: ignored